# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
unordered_multichain_mode: true
contracts:
  - name: PoolManager
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 indexed id, uint256 amount)
      - event: Donate(bytes32 indexed id, address indexed sender, uint256 amount0, uint256 amount1)
      - event: Initialize(bytes32 indexed id, address indexed currency0, address indexed currency1, uint24 fee, int24 tickSpacing, address hooks, uint160 sqrtPriceX96, int24 tick)
      - event: ModifyLiquidity(bytes32 indexed id, address indexed sender, int24 tickLower, int24 tickUpper, int256 liquidityDelta, bytes32 salt)
      - event: OperatorSet(address indexed owner, address indexed operator, bool approved)
      - event: OwnershipTransferred(address indexed user, address indexed newOwner)
      - event: ProtocolFeeControllerUpdated(address indexed protocolFeeController)
      - event: ProtocolFeeUpdated(bytes32 indexed id, uint24 protocolFee)
      - event: Swap(bytes32 indexed id, address indexed sender, int128 amount0, int128 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick, uint24 fee)
      - event: Transfer(address caller, address indexed from, address indexed to, uint256 indexed id, uint256 amount)
  - name: PositionManager
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 indexed id)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event: Subscription(uint256 indexed tokenId, address indexed subscriber)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed id)
      - event: Unsubscription(uint256 indexed tokenId, address indexed subscriber)
networks:
  - id: 1
    start_block: 0
    contracts:
      - name: PositionManager
        address:
          - 0xbD216513d74C8cf14cf4747E6AaA6420FF64ee9e
      - name: PoolManager
        address:
          - "0x000000000004444c5dc75cB358380D2e3dE08A90"
  - id: 10
    start_block: 0
    contracts:
      - name: PositionManager
        address:
          - 0x3C3Ea4B57a46241e54610e5f022e5c45859A1017
      - name: PoolManager
        address:
          - 0x9a13F98Cb987694C9F086b1F5eB990EeA8264Ec3
  - id: 8453
    start_block: 0
    contracts:
      - name: PositionManager
        address:
          - 0x7c5f5a4bbd8fd63184577525326123b519429bdc
      - name: PoolManager
        address:
          - 0x498581ff718922c3f8e6a244956af099b2652b2b
  - id: 42161
    start_block: 0
    contracts:
      - name: PositionManager
        address:
          - 0xd88f38f930b7952f2db2432cb002e7abbf3dd869
      - name: PoolManager
        address:
          - 0x360e68faccca8ca495c1b759fd9eee466db9fb32
  - id: 137
    start_block: 0
    contracts:
      - name: PositionManager
        address:
          - 0x1ec2ebf4f37e7363fdfe3551602425af0b3ceef9
      - name: PoolManager
        address:
          - 0x67366782805870060151383f4bbff9dab53e5cd6
  - id: 81457
    start_block: 0
    contracts:
      - name: PositionManager
        address:
          - 0x4ad2f4cca2682cbb5b950d660dd458a1d3f1baad
      - name: PoolManager
        address:
          - 0x1631559198a9e474033433b2958dabc135ab6446
  - id: 7777777
    start_block: 0
    contracts:
      - name: PositionManager
        address:
          - 0xf66c7b99e2040f0d9b326b3b7c152e9663543d63
      - name: PoolManager
        address:
          - 0x0575338e4c17006ae181b47900a84404247ca30f
  - id: 57073
    start_block: 0
    contracts:
      - name: PositionManager
        address:
          - 0x1b35d13a2e2528f192637f14b05f0dc0e7deb566
      - name: PoolManager
        address:
          - 0x360e68faccca8ca495c1b759fd9eee466db9fb32
  - id: 1868
    start_block: 0
    contracts:
      - name: PositionManager
        address:
          - 0x1b35d13a2e2528f192637f14b05f0dc0e7deb566
      - name: PoolManager
        address:
          - 0x360e68faccca8ca495c1b759fd9eee466db9fb32
  - id: 43114
    start_block: 0
    contracts:
      - name: PositionManager
        address:
          - 0xb74b1f14d2754acfcbbe1a221023a5cf50ab8acd
      - name: PoolManager
        address:
          - 0x06380c0e0912312b5150364b9dc4542ba0dbbc85
  - id: 56
    start_block: 0
    contracts:
      - name: PositionManager
        address:
          - 0x7a4a5c919ae2541aed11041a1aeee68f1287f95b
      - name: PoolManager
        address:
          - 0x28e2ea090877bf75740558f6bfb36a5ffee9e9df
  - id: 130
    hypersync_config:
      url: https://130.hypersync.xyz
    start_block: 0
    contracts:
      # - name: PositionManager
      #   address:
      #     -
      - name: PoolManager
        address:
          - 0x1F98400000000000000000000000000000000004
rollback_on_reorg: false
